spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

